version: '3.3'

services:
  db:
    image: postgres:15-alpine
    container_name: test_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - '5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  django:
    container_name: test_djangoproject
    build:
      context: .
    command: >
      sh -c "python3 manage.py collectstatic --noinput && 
             python3 manage.py migrate &&
             exec gunicorn core.wsgi:application -b 0.0.0.0:8000 --reload"
    volumes:
      - ./static/:/usr/src/app/admin_panel/public_html/static
    expose:
      - 8000
    restart: always
    env_file:
      - .env_dist
    depends_on:
      - db

volumes:
  pg_data:
  static:
