# Generated by Django 4.2.4 on 2023-09-07 09:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="Ячейка"),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="Вес"),
                ),
                (
                    "is_jackpot",
                    models.BooleanField(default=False, verbose_name="Джекпот"),
                ),
            ],
            options={
                "verbose_name": "Ячейка",
                "verbose_name_plural": "Ячейки",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "round_number",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Номер раунда"
                    ),
                ),
                (
                    "is_jackpot_drawn",
                    models.BooleanField(default=False, verbose_name="Джекпот выпал"),
                ),
                (
                    "cells",
                    models.ManyToManyField(
                        blank=True, to="roulette.cell", verbose_name="Ячейки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Раунд",
                "verbose_name_plural": "Раунды",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cell_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roulette.cell",
                        verbose_name="Ячейка",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roulette_rounds",
                        to="roulette.player",
                        verbose_name="Участник",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roulette_rounds",
                        to="roulette.round",
                        verbose_name="Раунд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раунд рулеток",
                "verbose_name_plural": "Раунды рулеток",
                "unique_together": {("round", "cell_number")},
            },
        ),
    ]
